### PR TITLE
Support vars and vars-files.

### LINKED ISSUE #55: Support passing --var
See https://github.com/cloudfoundry/cli/releases/tag/v6.37.0 "Variable Substitution" section and https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests

`cf push --vars-file vars.yml` is now a delightful thing. Can we please add `vars-file` to this resource + bump to v6.37 cli

### PR DESCRIPTION
**Pull request by jmcarp**
[Fixes #55]

Depends on https://github.com/contraband/autopilot/pull/52

### CODE REVIEW

**Comment by rogeruiz** [comment]
@vito I can't see the issue that's causing the failure. But is it possible to get an answer on this PR? We'd love to be able to use `vars-files` in our CF deployments using CI.

**Comment by vito** [comment]
@rogeruiz Sorry! We've got the upstream change merged now, so I can take a look at this again.

FWIW, @xoebus and I would like to hand this resource (and probably autopilot) over to someone else - ideally it would live in the `cloudfoundry` org alongside the `bosh-deployment-resource`. I'm not sure who'd own it though. I just don't think we're really giving this resource the attention that other people could be giving it, and it feels weird to have it part of the "core set" of resources.

**Comment by vito** [comment]
Thanks! Upstream `autopilot` has a new release out with the dependent changes, so merging now.

**Comment by xyloman** [comment]
Saw this and thought I would take it for a test run.  The only issue that I ran into was if the vars file is loaded from an input like a git resource I had to append /tmp/build/put in front of the directory in order for it to be found by cf push.  When I would not provide current_app_name I would get the following:

```
Incorrect Usage: The specified path 'pipelines-git/integration/vars.yml' does not exist.
```

Updating the vars-file path to 
```
      vars_files: 
      - /tmp/build/put/pipelines-git/integration/vars.yml
```
The CF push would work.

In either case if current_app_name was provided I would get the following error: 
```
	
error: The following flags cannot be used with deprecated usage: vars-file
	
error running command: exit status 1
```

I think this error is coming from the autopilot cf plugin.  Relative and absolute vars-file values result in the same error.

**Comment by squeedee** [comment]
I've annotated [the issue on autopilot](https://github.com/contraband/autopilot/issues/59#issuecomment-427452352)
It seems to me that this is a bug in the CLI.

**Pull request merged**
