### PR TITLE
Add support for setting application environment variables

### PR DESCRIPTION
**Pull request by spikymonkey**
Hi,

We've created a patch to allow environment variables to be set when applications are pushed. After the push, the specified variables are set using `cf set-env` and then the app is restaged. A map of env vars can be specified as part of the resource put declaration like this:

```yaml
put: my-cloud-foundry-resource
params:
  manifest: path/to/manifest.yml
  environment_variables:
    key: value
    key2: value2
```

We're finding this very useful for setting things like credentials and other changeable bits and pieces which can't be published in manifest files. Please let us know your thoughts!

### CODE REVIEW

**Comment by vito** [comment]
Cool! What's the effect of restaging? Does it cause the PaaS to eventually switch over the app to the newly staged bits or something?

**Comment by spikymonkey** [comment]
Yep, it'll cause the buildpack to run again, and so allows the apps to pick
up the new environment variables that have been set.

I'm wondering if we might be able to do things more efficiently than that
now... I haven't tried it yet but I'm wondering if by pushing the app using
the --no-start option, then setting env vars, and then starting the app, we
could get away with only one run of the buildpack... Might be a bit cleaner
and definitely quicker if so. I'll try it and find out.

**Comment by vito** [comment]
I think it might also cause downtime, which won't be very nice... Considering the resource is supposed to support zero-downtime pushes. :)

Perhaps the most airtight way to do this would be to modify the manifest before pushing? It's a but janky but allows us to keep the rest of the code sane (just a single `cf push` or `cf zero-downtime-push`).

**Comment by vito** [comment]
You may also be interested in using manifest inheritance; that way you can have your credentials in a separate sub-manifest that points at the main one (which can then live in a public repo).

See http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests

**Comment by spikymonkey** [comment]
Good point on the zero downtime deployments... I have to admit I know
nothing about this, so I'll have a play and see if I can find out whether
or not there's any way of doing them whilst picking up environment changes.

As for the manifest inheritance - we're already using that for some vars
which are less likely to change and which don't have any security
implications. It definitely works well for those cases.

There are two main problems I can think of with storing the credentials in
the manifests themselves. Firstly proliferation... We have a microservice
architecture so copying creds into many manifests doesn't really scale. You
could possibly get around this with some git submodule magic to share a
single common base manifest. But I think even then you'd end up exporting
the union of all app vars into each app's env - I'd rather just set the
minimum set for each app to work.

The other issue is just security. I'd rather not be storing keys in the
clear if we can avoid it, even if they're in private repos. By injecting
them at pipeline configuration time they don't need to be stored anywhere
near the code - we currently copy them in from an encrypted keystore when
running 'fly configure'.

**Comment by spikymonkey** [comment]
Hi again,

I've taken another crack at this. It now works by adding the environment variables to the manifest, before doing the cf push. This eliminates the need for a restage, which cuts the deployment time in half, and should mean that we're all good for zero-downtime deployments :)

**Comment by vito** [comment]
looks great, thanks! should be in the next release (0.56).

**Comment by xoebus** [comment]
:+1: This is a great addition and a neat method for doing it.

**Comment by spikymonkey** [comment]
Cool - thanks!

**Pull request merged**
